language: node_js
sudo: false
cache:
  yarn: true
node_js:
  - node
  - 10
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn install
jobs:
  include:
    - stage: build
        - NODE_ENV=PRODUCTION
      before_script: yarn clean
      script: yarn build
    - stage: test
      env:
        - NODE_ENV=TEST
      before_script: yarn clean
      script: yarn test
